"""1

Revision ID: d4feed40d17d
Revises: 
Create Date: 2025-12-29 07:04:21.839844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4feed40d17d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='服务名称（唯一）'),
    sa.Column('description', sa.Text(), nullable=True, comment='服务描述'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='服务编码（如：SV_001）'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='服务类型：consult/reserve/complaint'),
    sa.Column('status', sa.String(length=10), nullable=True, comment='状态：online/offline/maintenance'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='服务时长（分钟）'),
    sa.Column('price', sa.Float(), nullable=True, comment='服务价格（元）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户名（唯一）'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='加密后的密码'),
    sa.Column('role', sa.String(length=10), nullable=False, comment='角色：admin/agent/user'),
    sa.Column('email', sa.String(length=120), nullable=True, comment='邮箱（可选，唯一）'),
    sa.Column('phone', sa.String(length=11), nullable=True, comment='手机号（可选，唯一）'),
    sa.Column('real_name', sa.String(length=30), nullable=True, comment='真实姓名'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活（禁用/启用）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除标记'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间（UTC）'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='预约用户ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='服务ID'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='分配的客服ID'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='预约时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/confirmed/canceled/completed'),
    sa.Column('rating', sa.Integer(), nullable=True, comment='评分（1-5分）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='预约备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='发起会话的用户ID'),
    sa.Column('agent_id', sa.Integer(), nullable=True, comment='处理会话的客服ID'),
    sa.Column('service_id', sa.Integer(), nullable=True, comment='关联服务ID'),
    sa.Column('appointment_id', sa.Integer(), nullable=True, comment='关联预约ID'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='会话开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='会话结束时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/closed/timeout'),
    sa.Column('last_message_time', sa.DateTime(), nullable=True, comment='最后消息时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='发送者ID'),
    sa.Column('receiver_id', sa.Integer(), nullable=True, comment='接收者ID'),
    sa.Column('text', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('sentiment', sa.Float(), nullable=True, comment='情感分析得分（-1~1）'),
    sa.Column('message_type', sa.String(length=10), nullable=True, comment='消息类型：text/image/file'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('file_url', sa.String(length=255), nullable=True, comment='文件/图片URL（非文本消息）'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friend_relations')
    op.drop_table('chat_sessions')
    op.drop_table('appointments')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
